name: CI

on:
  workflow_call:
    inputs:
      ref:
        description: 'The ref to check out'
        required: true
        type: string
  push:
    branches:
      - main

permissions:
  contents: read # This is required for actions/checkout

jobs:
  CI:
    name: Quality Assurance
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        if: ${{ github.event_name == 'push' }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout
        if: ${{ github.event_name == 'workflow_call' }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Merge main
        run: |
          git fetch origin main
          git merge origin/main

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Compile
        run: yarn build

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test
