name: Verify Pull-Request Changes
on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  pull-requests: read

jobs:
  verify_pr_title:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  quality_assurance:
    name: Quality Assurance
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Merge main
        run: |
          git fetch origin main
          git merge origin/main

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Compile
        run: yarn build

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test

  generate_diff:
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read # This is required for actions/checkout
      pull-requests: write # This is required for creating a pull request

    name: Generate CDK Diff
    runs-on: ubuntu-latest
    needs:
      - verify_pr_title
      - quality_assurance
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Merge main
        run: |
          git fetch origin main
          git merge origin/main

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/oidc-gha-deployment
          role-session-name: github-action
          aws-region: ${{ vars.AWS_REGION }}

      - name: Run cdk diff
        uses: youyo/aws-cdk-github-actions@v2
        if: github.base_ref == 'main'
        env:
          AWS_ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID }}
          AWS_REGION: ${{ vars.AWS_REGION }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          cdk_subcommand: 'diff'
          actions_comment: true
