name: Verify Pull-Request Changes
on: [pull_request]

permissions:
  pull-requests: read

jobs:
  verify_pr_title:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  ci:
    secrets: inherit
    needs: verify_pr_title
    permissions:
      contents: read
    uses: ./.github/workflows/ci.yaml
    with:
      ref: ${{ github.sha }}

  generate_diff:
    needs: ci
    if: ${{ github.event.pull_request.merged == false && github.event.pull_request.base.ref == 'main' }}
    permissions:
      contents: read
      id-token: write # This is required for requesting the JWT
      pull-requests: write # This is required for creating a pull request
    secrets: inherit
    uses: ./.github/workflows/cdk-diff.yaml
    with:
      ref: ${{ github.sha }}
