name: Verify Pull-Request
on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  pull-requests: read

jobs:
  quality-assurance:
    runs-on: ubuntu-latest
    steps:
      - name: Compile
        run: yarn build
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test
