name: Verify Pull-Request
on: [pull_request]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          wip: true
      - name: Compile
        run: yarn build
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test
